### ISSUE TITLE
Seemingly a type mismatch in the return value of opjStreamRead

### ISSUE THREAD

**Issue by hejob** [uoregon-libraries/rais-image-server#37]
In src/openjpeg/image_stream.go, the value returned by opjStreamRead is opjMinusOne64 (type OPJ_UINT64), which seemingly mismatches the return type OPJ_SIZE_T under some compiling systems.

The compilation fails in local golang environment under MacOS Catalina with brew module openjpeg installed and used as a library. The problem is fixed after changing return value to opjMinusOneSizeT.

I think the reason it goes well in docker environment (both alpine and golang) is maybe that the two types references to the same type in ibopenjp2-7-dev. But in my MacOS local environment, the two types confirmed are u_longlong and u_long respectively.

I have made a push request trying to fix this.

**Comment by jechols** [comment]
ARGH.  Thanks for this, I'll take a look.

**Comment by jechols** [comment]
Your PR is merged and included in v4.0.2.  Docker image is still pending, though that shouldn't matter since those were never affected to begin with.
