### ISSUE TITLE
Unescape %2F in the IIIF identifier part of the path?

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/rais-image-server#7]
It seems that when Apache proxies, requests which include a query arg end up escaping the "%2F" to make it "%252F", so that when it's unescaped and sent to RAIS, it's "%2F" rather than "/".  Oddly this seems to *only* happen when a query arg is present.

It may be necessary to make RAIS unescape %2F itself.  This would allow more consistent parsing, because then (with `nocanon` turned off on the Apache rule), all incoming URLs appear to be escaped equally.  But are there dangerous edge cases here?  I can't imagine anybody actually using "%2F" in a filename, but you never know.  Though presumably that would get encoded to "%252F" so it would still work.  Right?

This needs some careful consideration.

**Comment by AndrewGearhart** [comment]
May no longer be necessary (at least for Open ONI source requests, see the last commit that I merged. https://github.com/open-oni/open-oni/commit/32017a603ea62a9d97a21da86824afc6bd1e1194#diff-7c158dd8cfe99945a97e5f4af5263fb5R52
Cheers, +A

**Comment by jechols** [comment]
Given that this can be tackled by changing how the proxying happens, I am going to call it a non-issue for RAIS.  IIIF IDs are crazy enough without trying to undo even more of the Apache proxying madness.
